version: '2'
services:
  wirid-app-front:
    container_name: wirid-app-front-docker
    image: 'ng-people-counter:1.0.0'
    #network_mode: host
    ports:
      #- "3030:8080"
      - "4200:80"
    #command: npm start
    restart: always

